"""empty message

Revision ID: 10c4d9dd72fe
Revises: 6518818a7cc2
Create Date: 2017-12-15 16:33:46.614123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10c4d9dd72fe'
down_revision = '6518818a7cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.drop_index('username2', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'username2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username2', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username2', 'user', ['username2'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###
